### ISSUE TITLE
No legend on the chart in the README

### ISSUE THREAD

**Issue by GP4cK** [simc/crimson#16]
I'm guessing the red is crimson.
What are the blue and green?

**Comment by simc** [comment]
should be fixed 😉

**Comment by GP4cK** [comment]
Mmm I still don't see it though :|

<img width="866" alt="image" src="https://user-images.githubusercontent.com/2680243/226146796-6eb7d103-7b28-4d17-aef3-a60ce502ad87.png">
